### PR TITLE
Merge live branch back into master

### PR DESCRIPTION
**Pull request by dra27**
- [x] opam-2.ocaml.org no longer pulling master branch (see https://github.com/ocaml/infrastructure/issues/19#issuecomment-1549486663)

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Can we simplify the ocurrent-deployer setup for this project once this is merged?

**Comment by dra27** [comment]
This PR is a "fake" merge commit - that is, it leaves the tree of master _exactly_ at the tree of live, discarding the master tree completely. The HEAD commit of this PR (64e843486ad91f270ddcbf639e0bfd451bcd8154), therefore, is identical to upstream/live @ 937ee346ed47e0fe59e647fa4a9b7a7402a79d36.

Just to show the working: `live` and `master` have an effective common base of bba77e776ed7a147e8c2389756b6b9d1dc672ee8 (that's **not** the merge-base, but earlier, since #205 was reverted on master). Ignoring PRs which were then merged to master and subsequently reverted, master since then contains #216, which is not needed as live has #215 instead, and #224, which is already on live.

**Comment by tmcgilchrist** [comment]
Thank you for fixing this @dra27 It will be great to get this piece of infrastructure finally sorted out.

**Comment by avsm** [comment]
I don't understand all the branching and merging going on here I'm afraid.  What needs to happen next to get this merged, and opam2web building off `main` again, and subsequently the expired PGP key at https://github.com/ocaml/infrastructure/issues/46 updated?

**Comment by dra27** [comment]
This PR just needs approving and merging! All it does is make master the same as live without any force pushing.

**Comment by dra27** [comment]
I don't know if the output from the visualizer is easier to interpret than GitHub's interface: this PR is literally one commit merging the live branch (which is presently deployed to opam.ocaml.org) into master (which is no longer deployed), leaving master with _exactly_ the same content as live.
image
(the "working" above is just an explanation for "copying" live to master doesn't lose anything)

**Review by avsm — APPROVED** [review]
Looks good, I believe dra27 :-)

**Comment by avsm** [comment]
But now, we do need to update the signing key live -- does that just have to go to the `master` branch and then pushed to `live` to be picked up the deployer?

**Comment by dra27** [comment]
That's right, yes - PR to `master` with the new key, it can be test-pushed to `staging` before merging (though probably not necessary for a static file) but should only be pushed to `live` after the PR's been merged on `master`. With this PR merged, the instructions/notes on https://github.com/ocaml-opam/opam2web#deployment are now actually correct 🙂

**Pull request merged**
