### PR TITLE
Hotfix unavailability of ocamlgraph.1.8.8 sources

### PR DESCRIPTION
**Pull request by dra27**
I'm working on a better proposal to propose to ocamlgraph's maintainers, but I think should unblock the deployment in the meantime.

### CODE REVIEW

**Comment by dra27** [comment]
Assuming this passes deployability, I propose pushing this commit to live, but not merging the PR - rather than editing the old URLs to point elsewhere, I'm hoping that instead the tarballs can be correctly put in the ocamlgraph repo (i.e. fix the 404 rather than change the URL)

**Comment by mtelvers** [comment]
Looks good to me.  I am running this locally, and it has long passed the failure point.

**Comment by dra27** [comment]
Upstream suggestion in https://github.com/backtracking/ocamlgraph/issues/140

**Comment by dra27** [comment]
The alternative will be to do a PR with https://github.com/dra27/opam-source-archives and update the package URLs in opam-repository, but personally I think it's slightly nicer for projects to host their own historical archives where possible 🙂

**Review by rjbou — APPROVED** [review]

**Pull request merged**
